
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
server:
    port: 8081
spring:
    datasource:
        password: '0000'
        url: jdbc:mysql://localhost:3306/inodev?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
    jackson:
        serialization:
            write_dates_as_timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:

                format_sql: true

                 


    mail:
        host: smtp.gmail.com
        password: yrcwhcqigacrldxp
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: moundherj@gmail.com
    servlet:
        multipart:
            max-file-size: 5MB


security:
  oauth2:
    sso:
      loginPath: /login
    client:
      clientId: 966540550860555
      clientSecret: 61c77606c85df76f63779eb6695dfac4
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
